// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykudkgqrmocxxhdtkxuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrdWRrZ3FybW9jeHhoZHRreHVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1OTQzMjAsImV4cCI6MjA3MjE3MDMyMH0.K-VFdRuUzWPNJ3tE49BXvsi2_-Yu8rr8UTLgDAtoaKI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});